"use client";

import Image from "next/image";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { 
  Zap, 
  Recycle, 
  Leaf, 
  DollarSign,
  Factory,
  Droplets,
  TrendingUp,
  CheckCircle,
  ArrowRight,
  Wind,
  Battery,
  Sprout
} from "lucide-react";
import { Navbar } from "@/app/components/storefront/Navbar";
import { Footer } from "@/app/components/storefront/Footer";

export default function GroBiogasPage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Navbar */}
      <Navbar />
      
      {/* Hero Section */}
      <section className="relative py-20 px-4 overflow-hidden bg-gradient-to-br from-emerald-50 via-white to-sky-50">
        <div className="absolute inset-0 bg-gradient-to-r from-emerald-500/5 to-sky-500/5"></div>
        <div className="container mx-auto max-w-6xl relative z-10">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div className="text-center lg:text-left">
              <Badge className="mb-4 bg-emerald-50 text-emerald-700 border-emerald-200 hover:bg-emerald-100">
                Renewable Energy Innovation
              </Badge>
              <h1 className="text-5xl md:text-7xl font-bold bg-gradient-to-r from-emerald-600 to-sky-600 bg-clip-text text-transparent mb-6">
                GroBiogas
              </h1>
              <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-6">
                Turning Agricultural Waste into Renewable Energy
              </h2>
              <p className="text-xl md:text-2xl text-gray-700 leading-relaxed font-light">
                GroBiogas is an innovative biogas production facility within the GroSpace ecosystem, 
                focused on converting agricultural waste into renewable energy. By transforming food waste, 
                animal waste, and other organic materials into biogas, GroBiogas plays a crucial role in 
                reducing waste while providing farmers with a sustainable energy source.
              </p>
            </div>
            <div className="relative">
              {/* Hero Biogas Image */}
              <div className="relative rounded-3xl overflow-hidden shadow-xl">
                <Image
                  src="/ecosystem.png"
                  alt="GroBiogas Renewable Energy and Waste Management"
                  width={600}
                  height={384}
                  className="w-full h-96 object-cover"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-emerald-900/20 to-transparent"></div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Overview Section */}
      <section className="py-16 px-4 bg-white">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center mb-12">
            <h2 className="text-4xl font-bold text-gray-900 mb-6">Sustainable Energy & Waste Management</h2>
            <p className="text-xl text-gray-600 max-w-4xl mx-auto leading-relaxed">
              The biogas generated by GroBiogas can be used for cooking, heating, or generating electricity, 
              while the byproducts of the process, such as liquid slurry, are repurposed into high-quality fertilizers like GroFast.
            </p>
          </div>

          {/* Overview Image Placeholder */}
          <div className="bg-gradient-to-br from-emerald-50 to-sky-50 rounded-3xl h-64 flex items-center justify-center border-2 border-dashed border-emerald-200 mb-12">
            <div className="text-center">
              <div className="w-20 h-20 bg-emerald-100 rounded-2xl flex items-center justify-center mx-auto mb-4">
                <Recycle className="w-10 h-10 text-emerald-600" />
              </div>
              <p className="text-gray-600 font-medium">Waste to Energy Process</p>
              <p className="text-sm text-gray-500">Circular Economy Visualization</p>
            </div>
          </div>

          <div className="grid md:grid-cols-2 gap-8">
            <div className="bg-white rounded-3xl shadow-lg border border-gray-100 p-8">
              <div className="w-16 h-16 bg-emerald-100 rounded-full flex items-center justify-center mb-6">
                <Leaf className="w-8 h-8 text-emerald-600" />
              </div>
              <h3 className="text-2xl font-bold text-gray-900 mb-4">Environmental Impact</h3>
              <p className="text-gray-600 leading-relaxed">
                With its dual focus on waste reduction and renewable energy, GroBiogas helps farmers lower their 
                environmental impact and adopt sustainable farming practices that contribute to a circular economy.
              </p>
            </div>

            <div className="bg-white rounded-3xl shadow-lg border border-gray-100 p-8">
              <div className="w-16 h-16 bg-sky-100 rounded-full flex items-center justify-center mb-6">
                <Zap className="w-8 h-8 text-sky-600" />
              </div>
              <h3 className="text-2xl font-bold text-gray-900 mb-4">Renewable Energy</h3>
              <p className="text-gray-600 leading-relaxed">
                The biogas produced provides farmers with a sustainable, cost-effective alternative to non-renewable 
                energy sources, powering farm operations, cooking, or generating electricity.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* What GroBiogas Does Section */}
      <section className="py-16 px-4 bg-gray-50/30">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center mb-12">
            <h2 className="text-4xl font-bold text-gray-900 mb-6">What Does GroBiogas Do?</h2>
            <p className="text-xl text-gray-600 max-w-4xl mx-auto leading-relaxed">
              GroBiogas converts organic waste into valuable energy and fertilizers through innovative anaerobic digestion processes.
            </p>
          </div>
          
          <div className="grid md:grid-cols-2 gap-8">
            <div className="bg-white rounded-3xl shadow-lg border border-gray-100 p-8 hover:shadow-xl transition-shadow duration-300">
              <div className="w-16 h-16 bg-emerald-100 rounded-full flex items-center justify-center mb-6">
                <Battery className="w-8 h-8 text-emerald-600" />
              </div>
              <h3 className="text-2xl font-bold text-gray-900 mb-4">Biogas Production</h3>
              <p className="text-gray-600 leading-relaxed mb-4">
                GroBiogas converts organic waste, including animal manure and food waste, into biogas through anaerobic digestion. 
                The biogas produced can be used as a renewable energy source for various applications, such as powering farm operations, 
                cooking, or generating electricity.
              </p>
              <p className="text-gray-600 leading-relaxed">
                This offers farmers a sustainable, cost-effective alternative to non-renewable energy sources.
              </p>
            </div>

            <div className="bg-white rounded-3xl shadow-lg border border-gray-100 p-8 hover:shadow-xl transition-shadow duration-300">
              <div className="w-16 h-16 bg-sky-100 rounded-full flex items-center justify-center mb-6">
                <Droplets className="w-8 h-8 text-sky-600" />
              </div>
              <h3 className="text-2xl font-bold text-gray-900 mb-4">Liquid Fertilizer Production</h3>
              <p className="text-gray-600 leading-relaxed mb-4">
                In addition to producing biogas, GroBiogas generates a nutrient-rich liquid slurry as a byproduct of the digestion process. 
                This slurry is processed into GroFast, a natural liquid fertilizer that helps farmers improve soil health and crop yields.
              </p>
              <p className="text-gray-600 leading-relaxed">
                By using GroFast, farmers can reduce their reliance on chemical fertilizers and promote healthier, more productive soils.
              </p>
            </div>

            <div className="bg-white rounded-3xl shadow-lg border border-gray-100 p-8 hover:shadow-xl transition-shadow duration-300">
              <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mb-6">
                <Recycle className="w-8 h-8 text-green-600" />
              </div>
              <h3 className="text-2xl font-bold text-gray-900 mb-4">Waste Repurposing</h3>
              <p className="text-gray-600 leading-relaxed mb-4">
                GroBiogas plays a vital role in reducing waste by repurposing organic materials that would otherwise be discarded. 
                Food waste from GroWaste and animal waste from poultry and livestock farms are collected and processed into valuable energy and fertilizers.
              </p>
              <p className="text-gray-600 leading-relaxed">
                This contributes to a zero-waste, circular farming system.
              </p>
            </div>

            <div className="bg-white rounded-3xl shadow-lg border border-gray-100 p-8 hover:shadow-xl transition-shadow duration-300">
              <div className="w-16 h-16 bg-purple-100 rounded-full flex items-center justify-center mb-6">
                <Wind className="w-8 h-8 text-purple-600" />
              </div>
              <h3 className="text-2xl font-bold text-gray-900 mb-4">Renewable Energy for Farmers</h3>
              <p className="text-gray-600 leading-relaxed mb-4">
                The biogas produced by GroBiogas can be used directly on the farm for various purposes. Farmers can use biogas 
                to power equipment, heat their facilities, or even sell excess energy to the grid, creating an additional revenue stream.
              </p>
              <p className="text-gray-600 leading-relaxed">
                By adopting biogas technology, farmers can reduce their energy costs while minimizing their carbon footprint.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Benefits Section */}
      <section className="py-16 px-4 bg-white">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center mb-12">
            <h2 className="text-4xl font-bold text-gray-900 mb-6">Why Farmers Should Use GroBiogas</h2>
            <p className="text-xl text-gray-600 max-w-4xl mx-auto leading-relaxed">
              GroBiogas offers numerous benefits that make it a valuable resource for farmers looking to reduce waste, 
              lower energy costs, and adopt more sustainable farming practices.
            </p>
          </div>

          {/* Benefits Image Placeholder */}
          <div className="bg-gradient-to-br from-emerald-50 to-sky-50 rounded-3xl h-64 flex items-center justify-center border-2 border-dashed border-emerald-200 mb-12">
            <div className="text-center">
              <div className="w-20 h-20 bg-emerald-100 rounded-2xl flex items-center justify-center mx-auto mb-4">
                <TrendingUp className="w-10 h-10 text-emerald-600" />
              </div>
              <p className="text-gray-600 font-medium">Farmer Benefits Overview</p>
              <p className="text-sm text-gray-500">Cost Savings & Sustainability</p>
            </div>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            <div className="bg-white rounded-2xl shadow-lg border border-gray-100 p-6 text-center hover:shadow-xl transition-shadow duration-300">
              <div className="w-16 h-16 bg-emerald-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <Wind className="w-8 h-8 text-emerald-600" />
              </div>
              <h4 className="text-lg font-semibold text-gray-900 mb-3">Renewable Energy Source</h4>
              <p className="text-gray-600">Biogas is a renewable and sustainable energy source that helps farmers reduce their reliance on fossil fuels while generating their own energy.</p>
            </div>
            
            <div className="bg-white rounded-2xl shadow-lg border border-gray-100 p-6 text-center hover:shadow-xl transition-shadow duration-300">
              <div className="w-16 h-16 bg-sky-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <DollarSign className="w-8 h-8 text-sky-600" />
              </div>
              <h4 className="text-lg font-semibold text-gray-900 mb-3">Cost Savings</h4>
              <p className="text-gray-600">By using biogas to power their farms, farmers can significantly lower their energy costs and improve their profitability.</p>
            </div>
            
            <div className="bg-white rounded-2xl shadow-lg border border-gray-100 p-6 text-center hover:shadow-xl transition-shadow duration-300">
              <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <Recycle className="w-8 h-8 text-green-600" />
              </div>
              <h4 className="text-lg font-semibold text-gray-900 mb-3">Waste Reduction</h4>
              <p className="text-gray-600">GroBiogas provides farmers with a way to repurpose organic waste, reducing environmental harm and contributing to sustainability.</p>
            </div>
            
            <div className="bg-white rounded-2xl shadow-lg border border-gray-100 p-6 text-center hover:shadow-xl transition-shadow duration-300">
              <div className="w-16 h-16 bg-purple-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <Sprout className="w-8 h-8 text-purple-600" />
              </div>
              <h4 className="text-lg font-semibold text-gray-900 mb-3">Natural Fertilizer for Soil Health</h4>
              <p className="text-gray-600">The liquid slurry produced is processed into GroFast, enhancing soil fertility and promoting healthy plant growth.</p>
            </div>
            
            <div className="bg-white rounded-2xl shadow-lg border border-gray-100 p-6 text-center hover:shadow-xl transition-shadow duration-300">
              <div className="w-16 h-16 bg-orange-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <TrendingUp className="w-8 h-8 text-orange-600" />
              </div>
              <h4 className="text-lg font-semibold text-gray-900 mb-3">Revenue Opportunities</h4>
              <p className="text-gray-600">Farmers who produce excess biogas can sell it back to the grid, creating an additional source of income.</p>
            </div>
          </div>
        </div>
      </section>

      {/* Ecosystem Role Section */}
      <section className="py-16 px-4 bg-gray-50/30">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center mb-12">
            <h2 className="text-4xl font-bold text-gray-900 mb-6">GroBiogas&apos;s Role in the GroSpace Ecosystem</h2>
            <p className="text-xl text-gray-600 max-w-4xl mx-auto leading-relaxed">
              GroBiogas is an integral part of the GroSpace value chain, playing a critical role in waste management, 
              renewable energy production, and soil health improvement.
            </p>
          </div>

          {/* Ecosystem Image Placeholder */}
          <div className="bg-gradient-to-br from-emerald-50 to-sky-50 rounded-3xl h-64 flex items-center justify-center border-2 border-dashed border-emerald-200 mb-12">
            <div className="text-center">
              <div className="w-20 h-20 bg-emerald-100 rounded-2xl flex items-center justify-center mx-auto mb-4">
                <Leaf className="w-10 h-10 text-emerald-600" />
              </div>
              <p className="text-gray-600 font-medium">GroSpace Ecosystem Integration</p>
              <p className="text-sm text-gray-500">Circular Economy Connections</p>
            </div>
          </div>

          <div className="space-y-8">
            <div className="bg-white rounded-3xl shadow-lg border border-gray-100 p-8">
              <div className="grid md:grid-cols-2 gap-8 items-center">
                <div>
                  <h3 className="text-2xl font-bold text-gray-900 mb-4">Waste Repurposing with GroWaste</h3>
                  <p className="text-gray-600 leading-relaxed">
                    GroBiogas works closely with GroWaste to collect food and animal waste from farms and processing plants. 
                    This waste is then converted into biogas and liquid fertilizer, ensuring that no organic material goes to waste.
                  </p>
                </div>
                <div className="flex justify-center">
                  <div className="w-16 h-16 bg-emerald-100 rounded-full flex items-center justify-center">
                    <Recycle className="w-8 h-8 text-emerald-600" />
                  </div>
                </div>
              </div>
            </div>

            <div className="bg-white rounded-3xl shadow-lg border border-gray-100 p-8">
              <div className="grid md:grid-cols-2 gap-8 items-center">
                <div className="order-2 md:order-1 flex justify-center">
                  <div className="w-16 h-16 bg-sky-100 rounded-full flex items-center justify-center">
                    <Battery className="w-8 h-8 text-sky-600" />
                  </div>
                </div>
                <div className="order-1 md:order-2">
                  <h3 className="text-2xl font-bold text-gray-900 mb-4">Energy Production and Use</h3>
                  <p className="text-gray-600 leading-relaxed">
                    The biogas produced provides farmers with a renewable energy source for farm operations, heating, or electricity generation. 
                    This helps reduce overall energy consumption and environmental footprint.
                  </p>
                </div>
              </div>
            </div>

            <div className="bg-white rounded-3xl shadow-lg border border-gray-100 p-8">
              <div className="grid md:grid-cols-2 gap-8 items-center">
                <div>
                  <h3 className="text-2xl font-bold text-gray-900 mb-4">Liquid Fertilizer Production for GroFast</h3>
                  <p className="text-gray-600 leading-relaxed">
                    GroBiogas produces GroFast, a natural liquid fertilizer made from nutrient-rich slurry. This fertilizer supports 
                    healthy plant growth and improves soil fertility, contributing to higher crop yields for farmers.
                  </p>
                </div>
                <div className="flex justify-center">
                  <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center">
                    <Droplets className="w-8 h-8 text-green-600" />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 px-4 bg-white">
        <div className="container mx-auto max-w-4xl text-center">
          <h2 className="text-4xl font-bold text-gray-900 mb-6">
            How to Get Started with GroBiogas
          </h2>
          <p className="text-xl text-gray-600 mb-8 leading-relaxed">
            Farmers interested in using biogas as a renewable energy source or accessing GroFast fertilizer can apply 
            through the GroSpace Marketplace. GroBiogas provides tailored biogas solutions based on the specific needs of each farm.
          </p>
          
          {/* CTA Image Placeholder */}
          <div className="bg-gradient-to-br from-emerald-50 to-sky-50 rounded-3xl h-48 flex items-center justify-center border-2 border-dashed border-emerald-200 mb-8">
            <div className="text-center">
              <div className="w-16 h-16 bg-emerald-100 rounded-full flex items-center justify-center mx-auto mb-3">
                <CheckCircle className="w-8 h-8 text-emerald-600" />
              </div>
              <p className="text-gray-600 font-medium">Get Started Today</p>
              <p className="text-sm text-gray-500">Application Process Visualization</p>
            </div>
          </div>

          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button size="lg" className="bg-gradient-to-r from-emerald-600 to-emerald-700 hover:from-emerald-700 hover:to-emerald-800 text-white px-8 py-3 rounded-xl shadow-lg hover:shadow-xl transition-all duration-200">
              Apply for GroBiogas
              <ArrowRight className="w-5 h-5 ml-2" />
            </Button>
            <Button asChild variant="outline" size="lg" className="border-2 border-gray-200 hover:border-emerald-500 hover:text-emerald-600 rounded-xl transition-all duration-200">
              <Link href="/about">Learn More About GroSpace</Link>
            </Button>
          </div>
          
          <div className="mt-12 bg-emerald-50 rounded-2xl p-8">
            <h3 className="text-2xl font-bold text-gray-900 mb-4">Join GroBiogas Today</h3>
            <p className="text-gray-600 leading-relaxed">
              Start turning waste into renewable energy and natural fertilizers for a more sustainable future. 
              Whether you&apos;re a small-scale farmer or a large commercial operation, GroBiogas provides the tools 
              and resources you need to create a cleaner, more efficient farm.
            </p>
          </div>
        </div>
      </section>

      {/* Footer */}
      <Footer />
    </div>
  );
}
